# frozen_string_literal: true

module Transeasy
  # Setup information
  class Config
    @@all_languages = [
      { lang: 'af-ZA', title: 'Afrikaans (South Africa)' },
      { lang: 'ar', title: 'Arabic' },
      { lang: 'ar-AE', title: 'Arabic (United Arab Emirates)' },
      { lang: 'ar-BH', title: 'Arabic (Bahrain)' },
      { lang: 'ar-DZ', title: 'Arabic (Algeria)' },
      { lang: 'ar-EG', title: 'Arabic (Egypt)' },
      { lang: 'ar-IQ', title: 'Arabic (Iraq)' },
      { lang: 'ar-JO', title: 'Arabic (Jordan)' },
      { lang: 'ar-KW', title: 'Arabic (Kuwait)' },
      { lang: 'ar-LB', title: 'Arabic (Lebanon)' },
      { lang: 'ar-LY', title: 'Arabic (Libya)' },
      { lang: 'ar-MA', title: 'Arabic (Morocco)' },
      { lang: 'ar-OM', title: 'Arabic (Oman)' },
      { lang: 'ar-QA', title: 'Arabic (Qatar)' },
      { lang: 'ar-SA', title: 'Arabic (Saudi Arabia)' },
      { lang: 'ar-SY', title: 'Arabic (Syria)' },
      { lang: 'ar-TN', title: 'Arabic (Tunisia)' },
      { lang: 'ar-YE', title: 'Arabic (Yemen)' },
      { lang: 'az-AZ', title: 'Azerbaijani (Azerbaijan)' },
      { lang: 'be-BY', title: 'Belarusian (Belarus)' },
      { lang: 'bg-BG', title: 'Bulgarian (Bulgaria)' },
      { lang: 'bn', title: 'Bengali' },
      { lang: 'bn-BD', title: 'Bengali (Bangladesh)' },
      { lang: 'bn-IN', title: 'Bengali (India)' },
      { lang: 'bs-BA', title: 'Bosnian (Bosnia and Herzegovina)' },
      { lang: 'ca-ES', title: 'Catalan (Spain)' },
      { lang: 'cs-CZ', title: 'Czech (Czech Republic)' },
      { lang: 'da-DK', title: 'Danish (Denmark)' },
      { lang: 'de', title: 'German' },
      { lang: 'de-DE', title: 'German (Germany)' },
      { lang: 'de-AT', title: 'German (Austria)' },
      { lang: 'de-CH', title: 'German (Switzerland)' },
      { lang: 'el-GR', title: 'Greek (Greece)' },
      { lang: 'en', title: 'English' },
      { lang: 'en-AU', title: 'English (Australia)' },
      { lang: 'en-CA', title: 'English (Canada)' },
      { lang: 'en-GB', title: 'English (United Kingdom)' },
      { lang: 'en-US', title: 'English (United States)' },
      { lang: 'es', title: 'Spanish' },
      { lang: 'es-ES', title: 'Spanish (Spain)' },
      { lang: 'es-MX', title: 'Spanish (Mexico)' },
      { lang: 'et-EE', title: 'Estonian (Estonia)' },
      { lang: 'fa-IR', title: 'Persian (Iran)' },
      { lang: 'fi-FI', title: 'Finnish (Finland)' },
      { lang: 'fr', title: 'French' },
      { lang: 'fr-FR', title: 'French (France)' },
      { lang: 'fr-CA', title: 'French (Canada)' },
      { lang: 'fr-CH', title: 'French (Switzerland)' },
      { lang: 'he-IL', title: 'Hebrew (Israel)' },
      { lang: 'hi-IN', title: 'Hindi (India)' },
      { lang: 'hr-HR', title: 'Croatian (Croatia)' },
      { lang: 'hu-HU', title: 'Hungarian (Hungary)' },
      { lang: 'id-ID', title: 'Indonesian (Indonesia)' },
      { lang: 'it-IT', title: 'Italian (Italy)' },
      { lang: 'ja-JP', title: 'Japanese (Japan)' },
      { lang: 'ko-KR', title: 'Korean (South Korea)' },
      { lang: 'ku-TR', title: 'Kurdish (Turkey)' },
      { lang: 'lt-LT', title: 'Lithuanian (Lithuania)' },
      { lang: 'lv-LV', title: 'Latvian (Latvia)' },
      { lang: 'mk-MK', title: 'Macedonian (Macedonia)' },
      { lang: 'ms-MY', title: 'Malay (Malaysia)' },
      { lang: 'nl-NL', title: 'Dutch (Netherlands)' },
      { lang: 'no-NO', title: 'Norwegian (Norway)' },
      { lang: 'pl-PL', title: 'Polish (Poland)' },
      { lang: 'pt', title: 'Portuguese' },
      { lang: 'pt-BR', title: 'Portuguese (Brazil)' },
      { lang: 'pt-PT', title: 'Portuguese (Portugal)' },
      { lang: 'ro-RO', title: 'Romanian (Romania)' },
      { lang: 'ru-RU', title: 'Russian (Russia)' },
      { lang: 'sk-SK', title: 'Slovak (Slovakia)' },
      { lang: 'sl-SI', title: 'Slovenian (Slovenia)' },
      { lang: 'sq-AL', title: 'Albanian (Albania)' },
      { lang: 'sr-RS', title: 'Serbian (Serbia)' },
      { lang: 'sv-SE', title: 'Swedish (Sweden)' },
      { lang: 'th-TH', title: 'Thai (Thailand)' },
      { lang: 'tr-TR', title: 'Turkish (Turkey)' },
      { lang: 'uk-UA', title: 'Ukrainian (Ukraine)' },
      { lang: 'ur-PK', title: 'Urdu (Pakistan)' },
      { lang: 'vi-VN', title: 'Vietnamese (Vietnam)' },
      { lang: 'zh', title: 'Chinese' },
      { lang: 'zh-CN', title: 'Chinese (Simplified)' },
      { lang: 'zh-TW', title: 'Chinese (Traditional)' }
    ].freeze
    mattr_accessor :all_languages

    @@all_translation_engines = [
      { name: 'Google', url: 'xx' },
      { name: 'Deepl', url: 'xx' },
      { name: 'Microsoft', url: 'xx' },
      { name: 'Yandex', url: 'xx' },
      { name: 'Libre', url: 'xx' },
      { name: 'Amazon', url: 'xx' },
      { name: 'Systran', url: 'xx' },
      { name: 'Baidu', url: 'xx' },
      { name: 'MyMemory', url: 'xx' },
      { name: 'World Lingo', url: 'xx' }
    ].freeze
    mattr_accessor :all_translation_engines
  end
end
