name: Rails 7.0 Test with MariaDB

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      mariadb:
        image: mariadb:latest
        allow-failure: true
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set up Database
        run: |
          cp config/database.yml.ci config/database.yml
          sed -i "s/username: root/username: test_user/g" config/database.yml
          sed -i "s/password:$/password: test_password/g" config/database.yml

      - name: Prepare Database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run Tests
        run: |
          bundle exec rspec
