name: Rails 7.0 Test with MariaDB

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test_mariadb:
    runs-on: ubuntu-20.04


    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306:3306
        env:
          MARIADB_ROOT_PASSWORD: root_password
          MARIADB_DATABASE: test_db
          MARIADB_USER: test_user
          MARIADB_PASSWORD: test_password
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        include:
          ### TEST ALL RUBY VERSIONS, USE DEFAULT GEMFILE
          - ruby: "3.0" ### must be quoted otherwise will be treated as "3" which will resolve to latest 3.x version
          - ruby: 3.1
          - ruby: 3.2

          ### RAILS VERSION TESTING
          - ruby: "3.0"
            env:
              RAILS_VERSION: "6.1.7.5"
          - ruby: "3.1"
            env:
              RAILS_VERSION: "7.0.7.1"

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
      DB_GEM: "mariadb"

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby }}"
          bundler-cache: true

      - name: Set up Database
        run: |
          cp config/database.yml.ci config/database.yml
          sed -i "s/username: root/username: test_user/g" config/database.yml
          sed -i "s/password:$/password: test_password/g" config/database.yml

      - name: Prepare Database
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run Brakeman
        run: bundle exec brakeman

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Bundler Audit
        run: bundle exec bundle-audit check --update

      - name: Run Tests
        run: |
          bundle exec rspec
